# Generated by Django 5.1.3 on 2024-11-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authorized',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
